changelog:
  exclude:
    labels:
      - release:ignore
    authors:
      - github-actions[bot]

  categories:
    - title: New Features
      labels:
        - release:feature
        - enhancement

    - title: Changed
      labels:
        - release:changed

    - title: Fixed
      labels:
        - release:fix
        - bug

    - title: Maintenance
      labels:
        - release:maintenance
        - dependencies
        - documentation

    - title: Other Changes
      labels:
        - "*"
